version: '2'
services:
  he-auth-service:
    build: .
    environment:
      HE_IDENTITY_PORTAL_ENDPOINT: "https://example.com"
      HE_AUTH_JWT_SECRET: secret
      MONGO: "mongodb://mongo:27017"
      HE_AUTH_SSL_PASS: default
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    ports:
      - "8080:3000"
    depends_on:
      - vault
    volumes:
      - ./certs:/usr/src/app/certs
  vault:
    image: vault:0.6.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      # need to bind to 0.0.0.0 so that it accepts remote connections (!localhost)
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
