version: '2'
services:
  he-auth-service:
    build: .
    environment:
      HE_IDENTITY_PORTAL_ENDPOINT: "https://example.com"
      HE_AUTH_JWT_SECRET: "default"
      MONGO: "mongodb://mongo:27017"
      HE_AUTH_SSL_PASS: "default"
    ports:
      - "8080:3000"
    depends_on:
      - vault
  vault:
    image: vault:0.6.1
  mongo:
    image: mongo:3.3